apiVersion: v1
kind: Secret
metadata:
  name: innosistemas-secrets
  namespace: innosistemas
type: Opaque
stringData:
  db-password: "password"
  db-username: "postgres"
  jwt-secret: "dev-secret-key-feature4"